//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livraria.Dominio.arquivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livro
    {
        public Livro()
        {
            this.Autor = new HashSet<Autor>();
        }
    
        public int IdLivro { get; set; }
        public string Nome { get; set; }
        public Nullable<decimal> Preco { get; set; }
        public Nullable<System.DateTime> DataPublicacao { get; set; }
    
        public virtual ICollection<Autor> Autor { get; set; }
    }
}
